version: "3.8"

services:
  train:
    profiles: ["donotstart"]
    build: .
    image: microplastics-predict:latest
    # The modern way to request NVIDIA GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HYDRA_FULL_ERROR=1
    volumes:
      - /mnt/ssd2:/mnt/ssd2:ro
      - /mnt/ssd3:/mnt/ssd3:ro
      - ${PROJECT_DIR}/.git:/app/.git:ro
      - ${PROJECT_DIR}/outputs:/app/outputs
      - ${PROJECT_DIR}/mlflow.db:/app/mlflow.db
      - ${PROJECT_DIR}/checkpoints:/app/checkpoints
      - ${PROJECT_DIR}/main.py:/app/main.py
      - ${PROJECT_DIR}/configs:/app/configs
      - ${PROJECT_DIR}/src/Data:/app/src/Data
      - ${PROJECT_DIR}/src/Engine:/app/src/Engine
      - ${PROJECT_DIR}/src/Models:/app/src/Models
      - ${PROJECT_DIR}/src/utils:/app/src/utils
    command: >
      python main.py
      mode=all
      data.spectra_per_plastic=64
      seed=0

  mlflow-ui:
    image: microplastics-predict:latest
    ports:
      - "5000:5000"
    volumes:
      - ${PROJECT_DIR}/mlflow.db:/app/mlflow.db
    # Environment variable for your custom SQLite library
    environment:
      - LD_PRELOAD=/usr/local/lib/libsqlite3.so.0
    command: >
      mlflow ui
      --backend-store-uri sqlite:////app/mlflow.db
      --host 0.0.0.0
      --port 5000

  jupyter:
    build: .
    image: microplastics-predict:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_PRELOAD=/usr/local/lib/libsqlite3.so.0
    ports:
      - "8888:8888"
    volumes:
      - /mnt/ssd2:/mnt/ssd2:ro
      - /mnt/ssd3:/mnt/ssd3:ro
      - ${PROJECT_DIR}/outputs:/app/outputs
      - ${PROJECT_DIR}/mlflow.db:/app/mlflow.db
      - ${PROJECT_DIR}/checkpoints:/app/checkpoints
      - ${PROJECT_DIR}/src/Data:/app/src/Data
      - ${PROJECT_DIR}/src/Engine:/app/src/Engine
      - ${PROJECT_DIR}/src/Models:/app/src/Models
      - ${PROJECT_DIR}/src/utils:/app/src/utils
      - ${PROJECT_DIR}/configs:/app/configs
      - ${PROJECT_DIR}/notebooks:/app/notebooks
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --ServerApp.token=''
      --ServerApp.password=''
      --notebook-dir=/app
    working_dir: /app
