defaults:
  - /domain/bacteria/data: default
  - /domain/bacteria/model: aacnn
  - /domain/bacteria/trainer: default
  - /domain/bacteria/inference: default

mlflow:
  experiment_name: "bacteria_full_augmentation"
