defaults:
  - /domain/pollen/data: default
  - /domain/pollen/model: aacnn
  - /domain/pollen/trainer: default
  - /domain/pollen/inference: default

mlflow:
  experiment_name: "pollen_full_augmentation"
