# configs/config.yaml
defaults:
  - model: aacnn
  - data: default
  - trainer: default
  - _self_

mlflow:
  tracking_uri:    "sqlite:////home/eirikmagnussen/Projects/microplastics/mlflow.db"
  experiment_name: "microplastics"

mode: all  
ckpt_path: null
seed: 42  
background_idx: 0  
top_k_save: 3
pred_store_path: "/app/outputs/predictions.lmdb"
project_name: "microplastics_classification"
