# configs/config.yaml
defaults:
  - model: aacnn
  - data: default
  - trainer: default
  - _self_

mode: all  
ckpt_path: null
seed: 42  
background_idx: 0  
top_k_save: 3
pred_store_path: "/mnt/ssd3/eirik/ProcessedData/saved_predictions.zarr"
project_name: "microplastics_classification"
